// Package message provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package message

import (
	"encoding/json"
)

const (
	MySecurityScopes = "MySecurity.Scopes"
)

// Defines values for BroadcastMessageChannel.
const (
	Alert     BroadcastMessageChannel = "alert"
	News      BroadcastMessageChannel = "news"
	Promotion BroadcastMessageChannel = "promotion"
)

// Defines values for MessageStatus.
const (
	Read     MessageStatus = "read"
	Received MessageStatus = "received"
	Sending  MessageStatus = "sending"
	Sent     MessageStatus = "sent"
)

// Defines values for MessageType.
const (
	Abstract    MessageType = "abstract"
	Broadcast   MessageType = "broadcast"
	Sitemessage MessageType = "sitemessage"
	Sms         MessageType = "sms"
	Wechat      MessageType = "wechat"
)

// BroadcastMessage defines model for BroadcastMessage.
type BroadcastMessage struct {
	Channel *BroadcastMessageChannel `json:"channel,omitempty"`

	// Content 消息内容
	Content string        `json:"content"`
	Id      int64         `json:"id"`
	Status  MessageStatus `json:"status"`
	Type    MessageType   `json:"type"`
}

// BroadcastMessageChannel defines model for BroadcastMessage.Channel.
type BroadcastMessageChannel string

// Message defines model for Message.
type Message struct {
	// Content 消息内容
	Content string        `json:"content"`
	Id      int64         `json:"id"`
	Status  MessageStatus `json:"status"`
	Type    MessageType   `json:"type"`
}

// MessageListResponse defines model for MessageListResponse.
type MessageListResponse struct {
	Messages *[]Message `json:"messages,omitempty"`
}

// MessageStatus defines model for MessageStatus.
type MessageStatus string

// MessageType defines model for MessageType.
type MessageType string

// SMSMessage defines model for SMSMessage.
type SMSMessage struct {
	// Content 消息内容
	Content string `json:"content"`
	Id      int64  `json:"id"`

	// PhoneNumber 接收手机号
	PhoneNumber string        `json:"phone_number"`
	Status      MessageStatus `json:"status"`
	Type        MessageType   `json:"type"`
}

// SiteMessage defines model for SiteMessage.
type SiteMessage struct {
	// Content 消息内容
	Content string        `json:"content"`
	Id      int64         `json:"id"`
	Status  MessageStatus `json:"status"`
	Type    MessageType   `json:"type"`

	// UserId 接收用户ID
	UserId int64 `json:"user_id"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// CreateBroadcastMessageJSONBody defines parameters for CreateBroadcastMessage.
type CreateBroadcastMessageJSONBody struct {
	union json.RawMessage
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateBroadcastMessageJSONRequestBody defines body for CreateBroadcastMessage for application/json ContentType.
type CreateBroadcastMessageJSONRequestBody CreateBroadcastMessageJSONBody
